kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.clusterName }}-tls-cert
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  tls.crt: >-
    {{ .Values.customTlsCertificate.crt}}
  tls.key: >-
    {{ .Values.customTlsCertificate.key}}
type: Opaque
